[package]
name = "num_subarray_product_less_than_k"
version = "0.1.0"
authors = ["James Shoaf <james.s.shoaf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
