[package]
name = "array_formation_through_concatenation"
version = "0.1.0"
authors = ["James <james.s.shoaf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
